apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: locust-worker
  labels:
    name: locust-worker
spec:
  replicas: ${WORKER_REPLICAS}
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
        - name: locust-worker
          image: ${LOCUST_IMAGE}
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi    
            requests:
              cpu: 100m
              memory: 128Mi             
          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER
              value: locust-master
            - name: TARGET_HOST
              value: ${TARGET_HOST}
          envFrom:
            - configMapRef:
                name: locust-tasks
                optional: false
          volumeMounts:
            - name: all-in-one
              mountPath: /locust-tasks
              readOnly: true
      volumes:
        - name: all-in-one
          projected:
            sources:
              - configMap:
                  name: locust-tasks
                  items:
                    - key: tasks.py
                      path: tasks.py